import { Router } from 'express';
import albumItemsRouter from './album-items';
import autoMeasureSettingsRouter from './auto-measure-settings';
import calibrationSettingsRouter from './calibration-settings';
import calibrationsRouter from './calibrations';
import cameraSettingRouter from './camera-setting';
import lineColorSettingRouter from './line-color-setting';
import genericSettingRouter from './generic-setting';
import otherSettingRouter from './other-setting';
import reportHeaderSettingRouter from './report-header-setting';
import serialPortSettingRouter from './serial-port-setting';
import depthImageSettingsRouter from './depth-image-settings';
import factoryResetRouter from './factory-reset';
import hardnessMachineRouter from './hardness-machine';
import healthRouter from './health';
import machineSettingsRouter from './machine-settings';
import measurementsRouter from './measurements';
import micrometerConfigRouter from './micrometer-config';
import patternProgramsRouter from './pattern-programs';
import testRecordsRouter from './test-records';
import toolbarStatesRouter from './toolbar-states';
import xyzPlatformRouter from './xyz-platform';
import xyzPlatformStatesRouter from './xyz-platform-states';

const router = Router();

router.use('/health', healthRouter);
router.use('/machine', hardnessMachineRouter);
router.use('/machine-settings', machineSettingsRouter);
router.use('/measurements', measurementsRouter);
router.use('/micrometer-config', micrometerConfigRouter);
router.use('/auto-measure-settings', autoMeasureSettingsRouter);
router.use('/calibration-settings', calibrationSettingsRouter);
router.use('/calibrations', calibrationsRouter);
router.use('/line-color-setting', lineColorSettingRouter);
router.use('/serial-port-setting', serialPortSettingRouter);
router.use('/camera-setting', cameraSettingRouter);
router.use('/generic-setting', genericSettingRouter);
router.use('/other-setting', otherSettingRouter);
router.use('/report-header-setting', reportHeaderSettingRouter);
router.use('/test-records', testRecordsRouter);
router.use('/xyz-platform-states', xyzPlatformStatesRouter);
router.use('/xyz-platform', xyzPlatformRouter);
router.use('/pattern-programs', patternProgramsRouter);
router.use('/depth-image-settings', depthImageSettingsRouter);
router.use('/album-items', albumItemsRouter);
router.use('/toolbar-states', toolbarStatesRouter);
router.use('/factory-reset', factoryResetRouter);

export default router;
